<?php

/**
 * Implements hook_mail().
 */
function custom_module_mail($key, &$message, $params) {
    switch ($key) {
        case 'contact':
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = t('Hello from @site', ['@site' => \Drupal::config('system.site')->get('name')]);
            $message['body'][] = $params['message'];
            break;
    }
}
